name = "sky130hd"

# Process node
process = 130

stackup = "5M1LI"
# default_corner = "tt"

#-----------------------------------------------------
# Tech/Libs
# ----------------------------------------------------
lib_files = ["lib/sky130_fd_sc_hd__tt_025C_1v80.lib"]
tech_lef = "lef/sky130_fd_sc_hd.tlef"
std_cell_lef = "lef/sky130_fd_sc_hd_merged.lef"
gds_files = ["gds/sky130_fd_sc_hd.gds"]

# derate_tcl = "..."
setrc_tcl = "setRC.tcl"

# Dont use cells to ease congestion
# Specify at least one filler cell if none

# The *probe* are for inserting probe points and have metal shapes
# on all layers.
# *lpflow* cells are for multi-power domains
dont_use_cells = [
    "sky130_fd_sc_hd__probe_p_8",
    "sky130_fd_sc_hd__probec_p_8",
    "sky130_fd_sc_hd__lpflow_bleeder_1",
    "sky130_fd_sc_hd__lpflow_clkbufkapwr_1",
    "sky130_fd_sc_hd__lpflow_clkbufkapwr_16",
    "sky130_fd_sc_hd__lpflow_clkbufkapwr_2",
    "sky130_fd_sc_hd__lpflow_clkbufkapwr_4",
    "sky130_fd_sc_hd__lpflow_clkbufkapwr_8",
    "sky130_fd_sc_hd__lpflow_clkinvkapwr_1",
    "sky130_fd_sc_hd__lpflow_clkinvkapwr_16",
    "sky130_fd_sc_hd__lpflow_clkinvkapwr_2",
    "sky130_fd_sc_hd__lpflow_clkinvkapwr_4",
    "sky130_fd_sc_hd__lpflow_clkinvkapwr_8",
    "sky130_fd_sc_hd__lpflow_decapkapwr_12",
    "sky130_fd_sc_hd__lpflow_decapkapwr_3",
    "sky130_fd_sc_hd__lpflow_decapkapwr_4",
    "sky130_fd_sc_hd__lpflow_decapkapwr_6",
    "sky130_fd_sc_hd__lpflow_decapkapwr_8",
    "sky130_fd_sc_hd__lpflow_inputiso0n_1",
    "sky130_fd_sc_hd__lpflow_inputiso0p_1",
    "sky130_fd_sc_hd__lpflow_inputiso1n_1",
    "sky130_fd_sc_hd__lpflow_inputiso1p_1",
    "sky130_fd_sc_hd__lpflow_inputisolatch_1",
    "sky130_fd_sc_hd__lpflow_isobufsrc_1",
    "sky130_fd_sc_hd__lpflow_isobufsrc_16",
    "sky130_fd_sc_hd__lpflow_isobufsrc_2",
    "sky130_fd_sc_hd__lpflow_isobufsrc_4",
    "sky130_fd_sc_hd__lpflow_isobufsrc_8",
    "sky130_fd_sc_hd__lpflow_isobufsrckapwr_16",
    "sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_1",
    "sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_2",
    "sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_4",
    "sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_4",
    "sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_1",
    "sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_2",
    "sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_4",
]
fill_cells = [
    "sky130_fd_sc_hd__fill_1",
    "sky130_fd_sc_hd__fill_2",
    "sky130_fd_sc_hd__fill_4",
    "sky130_fd_sc_hd__fill_8",
]

tiehi_cell = "sky130_fd_sc_hd__conb_1"
tiehi_port = "HI"
tielo_cell = "sky130_fd_sc_hd__conb_1"
tielo_port = "LO"

min_buf_cell = "sky130_fd_sc_hd__buf_4"
min_buf_ports = ["A", "X"]


#
# Define fill cells
# -----------------------------------------------------
#  Yosys
#  ----------------------------------------------------
# Set the TIEHI/TIELO cells
# These are used in yosys synthesis to avoid logical 1/0's in the netlist
# Used in synthesis
# Yosys mapping files
latch_map_file = "cells_latch_hd.v"
clkgate_map_file = "cells_clkgate_hd.v"
adder_map_file = "cells_adders_hd.v"
#
# Define ABC driver and load
abc_driver_cell = "sky130_fd_sc_hd__buf_1"
abc_load_in_ff = 5

#--------------------------------------------------------
# Floorplan
# -------------------------------------------------------

# Placement site for core cells
# This can be found in the technology lef
place_site = "unithd"

# IO Placer pin layers
io_placer_h = "met3"
io_placer_v = "met2"

# Define default PDN config
pdn_tcl = "pdn.tcl"

# Endcap and Welltie cells
tapcell_tcl = "tapcell.tcl"

macro_place_halo = [40, 40]
macro_place_channel = [80, 80]

#---------------------------------------------------------
# Place
# --------------------------------------------------------
# default cell padding for cells 
cell_pad_in_sites_global_placement = 1
cell_pad_in_sites_detail_placement = 0
#

place_density = 0.60

# Cell padding in SITE widths to ease rout-ability
cell_pad_in_sites = 4
# 
# --------------------------------------------------------
#  CTS
#  -------------------------------------------------------
# TritonCTS options
cts_buf_cell = "sky130_fd_sc_hd__clkbuf_4"

# ---------------------------------------------------------
#  Route
# ---------------------------------------------------------
# FastRoute options
min_routing_layer = "met1"
max_routing_layer = "met5"
#
# Define fastRoute tcl
fastroute_tcl = "fastroute.tcl"

# KLayout technology file
klayout_tech_file = "sky130hd.lyt"
# Layer properties file
klayout_layer_prop_file = "sky130hd.lyp"

# Rules for metal fill
fill_config = "fill.json"

# Template definition for power grid analysis
template_pga_cfg = "template_pga.cfg"


# ---------------------------------------------------------
#  IR Drop
# ---------------------------------------------------------
voltage = 1.8
# IR drop estimation supply net name to be analyzed and supply voltage variable
# For multiple nets: PWR_NETS_VOLTAGES  = "VDD1 1.8 VDD2 1.2"
pwr_nets_voltages = { VDD = 1.8 }
gnd_nets_voltages = { VSS = 0.0 }
ir_drop_layer = "met1"

# OpenRCX extRules
rcx_rules = "rcx_patterns.rules"
